### ISSUE TITLE
Please add Fedora instructions to install64.txt

### ISSUE THREAD

**Issue by ssb22** [rtrussell/BBCSDL#2]
The website at http://www.bbcbasic.co.uk/bbcsdl/ has download links, including [Linux edition (64-bit, x86 CPU)](http://www.rtr.myzen.co.uk/bbclinux.zip) which contains a file `install64.txt` including the text:

    Installing SDL 2.0 on Linux systems:
    64-bit Debian / Mint / Ubuntu:
     sudo apt-get install libsdl2-2.0-0
     sudo apt-get install libsdl2-ttf-2.0-0
     sudo apt-get install libsdl2-net-2.0-0

Unfortunately I was unable to find the `install64.txt` file (or code that generates it) in this repository—did I miss something?—but I just wondered if Fedora instructions could be added to the above:

    sudo dnf install SDL2 SDL2_ttf SDL2_net

Thanks.

**Comment by rtrussell** [comment]
Fedora instructions added, and install64.txt included in this repository (in the bin/linux directory) as requested.
