### ISSUE TITLE
Syncronise PWM channels in sound_sdl.c

### ISSUE THREAD

**Issue by Memotech-Bill** [rtrussell/BBCSDL#25]
It is possible to start two PWM channels simultaneously an synchronously by using:

    pwm_init(audio_pin_slice_R, &config, false);
    pwm_init(audio_pin_slice_L, &config, false);
    pwm_set_mask_enabled (( 1 << audio_pin_slice_L ) | ( 1 << audio_pin_slice_R));

**Comment by rtrussell** [comment]
> It is possible to start two PWM channels simultaneously an synchronously by using:

That may be so, but it's not what you want.  In practice the main consideration is to reduce the 'crackling' in the right channel (only), which experimentally seemed to be at a minimum when the left channel is lagging slightly behind the right channel.  This may have to do with the fact that you cannot update the two compare values simultaneously, but I'm not sure.

According to the documentation "_The counter compare register is double-buffered in hardware_" which ought to mean that the instant at which you update the compare value is not critical, so long as you avoid a narrow band.  But that is not what I found in practice, just a small change to the relative timing between the two channels seemed to affect the 'crackling', so I'm not sure what's going on internally.

It seems to me that the RP2040 was designed with the expectation that stereo audio outputs would come from the same slice.  Not only does each slice have two comparators (A and B) but then you **can** update both values in the same call: _pwm_set_both_levels()_.  It's a shame the reference design doesn't do this.
