### ISSUE TITLE
'const void *a' unknown size ln 4791, and 'const void *b' unknown size same line, in SDL2_gfxPrimitives.c

### ISSUE THREAD

**Issue by ghost** [rtrussell/BBCSDL#26]
well uhh I tried using your gfx primitives and it seems to not work giving me the error above.

**Comment by ghost** [comment]
dont know if this is a good or permanent fix but I just changed it to a float and it works.

**Comment by rtrussell** [comment]
> I tried using your gfx primitives and it seems to not work giving me the error above.

What compiler are you using?  The code compiles correctly with **GCC** and **Clang** but it probably relies (accidentally) on an extension that they support but (for example) Microsoft compilers do not.  Thanks for letting me know.

**Comment by rtrussell** [comment]
> dont know if this is a good or permanent fix but I just changed it to a float and it works.

Not sure exactly what change you've made (you've got to be careful, because it's easy to break the pointer arithmetic), but try this:

`	float diff = *((float *)a + 1) - *((float *)b + 1) ;
`
