### ISSUE TITLE
ENVELOPE pitch auto-repeat behaviour does not match the BBC Micro

### ISSUE THREAD

**Issue by ssb22** [rtrussell/BBCSDL#3]
Referring to the [ENVELOPE section in the manual](http://www.bbcbasic.co.uk/bbcwin/manual/bbcwin4.html#envelope), if I run, for example:

    ENVELOPE 1, 3, 0, 4*4, 4*3, 1, 1, 1, 126,0,0,-126,126,126
    SOUND 1, 1, 100, 200

a BBC Micro emulator plays `C-E-G-C-E-G-C-E-G` etc (rapidly repeating arpeggiated C Major triad) for 10 seconds.  This technique can be used to simulate chords of up to 3 notes on only one sound channel, leaving the other channels free to play additional notes.

But putting the above into BBCSDL gives `C-E-G-B-D'-F#'-A'-C#''` etc, with the pitch rising to the top of the range and then wrapping around to the bottom.  It seems BBCSDL's idea of "auto repeat the pitch envelope" is for the repeated Section 1 to start at the pitch where the previous Section 3 ended, whereas the "real" BBC resets the pitch to that specified by `SOUND` at the point where the pitch envelope starts to auto-repeat.  That means BBC Micro programs that use `ENVELOPE` techniques like this will not sound right on BBCSDL.

It is possible to work around the issue by limiting such arpeggiated envelopes to two notes per channel (instead of three), and adding a zero-length third step that brings the pitch back to its starting point.  For example, the following will work identically on the BBC Micro and in BBCSDL (except that BBCSDL plays everything one octave lower i.e. half the frequency, but I guess that difference is intentional) :

    ENVELOPE 1, 3, 0, 4*4, -4*4, 1, 1, 0, 126,0,0,-126,126,126
    SOUND 1, 1, 100, 200

**Comment by rtrussell** [comment]
Yes.  Unfortunately any modification to improve compatibility with the BBC Micro would inevitably worsen compatibility with 'BBC BASIC for Windows', which has worked the same way for 20 years!  The only way to resolve this satisfactorily would be to introduce some way to allow the programmer to choose which of the two behaviours he wants.  I would welcome any suggestions.

The octave-lower pitch is indeed intentional; in my opinion it makes better use of the 8-bit pitch range. Also because some of the waveforms that can be selected with *VOICE contain high-order harmonics I want those to be in the range that the Direct Digital Synthesiser can produce without excessive aliasing.

**Comment by rtrussell** [comment]
I've realised that I have already set a precedent by using bit 7 of the *TEMPO value to determine whether SOUND channel 0 is 'noise' (the default) or a fourth tone channel.  In principle I could use bit 6 to control the ENVELOPE repeat behaviour, if it proves to be feasible.

**Comment by ssb22** [comment]
I guess so, as long as nobody's using `*TEMPO 64` or higher for really long notes :)

**Comment by rtrussell** [comment]
> I guess so, as long as nobody's using *TEMPO 64 or higher for really long notes :)

They can't, the largest value accepted by BBCSDL is *TEMPO 10 (twice the default 5 ms).  The fix will be in the next release.

**Comment by ssb22** [comment]
Thanks.  For [MIDI Beeper](https://ssb22.user.srcf.net/mwrhome/midi-beeper.html)'s BBC BASIC mode I added a `*TEMPO 69` if `INKEY$(-256)` returns `"s"` or `"S"` and a 3-note arpeggiated envelope is needed (which happens only if the input MIDI file sounds 7 or more notes at a time; if 6 or fewer then it can make do with 2-note envelopes, in which case it now adds a 0-length 3rd section to undo the pitch change so as to be compatible with older versions of BBC BASIC for SDL and BBC BASIC for Windows).  I also put in an `INKEY(-256)` check to make the code adjust which octave it uses so as to get the same result on Acorn's BBC BASIC as on BBC BASIC for SDL/Windows.  (This is all a bit "academic" because any machine capable of running BBC BASIC for SDL with sound should also be capable of playing the MIDI file with Timidity or similar, but somebody out there might want to add some music to a BBC BASIC program which they'd like to be compatible with both the real BBC and BBC BASIC for SDL / Windows, which is now possible.)

I guess another thing you might want to document somewhere is that the pitches used by BBC BASIC for SDL are more musically in tune than the pitches used by the original BBC Micro, but I hope it's very unlikely that anybody would want to undo that!  The SN76489 chip in the BBC Micro is limited to generating frequencies that are integer divisors of 125000—I'm not sure exactly how the OSWORD pitch parameters get mapped onto the chip's `N` register, but even the best possible mapping starts to drift from concert pitch by 5% of a semitone by the time we get to the F above concert A, and 10% in the octave above that.  MIDI files converted to BBC BASIC certainly seem to sound more "in tune" on BBC BASIC for SDL than they do on BeebEm3.

**Comment by rtrussell** [comment]
> I added a *TEMPO 69 if INKEY$(-256) returns "s" or "S"

Omitting the *TEMPO altogether will have the same effect (I've made the modified, more BBC Micro-like, behaviour the default).

> I guess another thing you might want to document somewhere is that the pitches used by BBC BASIC for SDL are more musically in tune than the pitches used by the original BBC Micro,

The BBC Micro's frequencies are more accurate at the low end than the high end (because it's a programmable divider) but mine are more accurate at the high end than the low end (because of Direct Digital Synthesis)!  The lowest note in mine uses an increment of 745 so it's not **that** accurate really (about 1/40 semitone, or 2.5 cents).

**Comment by ssb22** [comment]
Thanks, OK I can take out the `*TEMPO` then :)

**Comment by rtrussell** [comment]
Changes implemented in v1.13a released today.  I'd be very pleased to see a program which demonstrates the 'arpeggiated envelopes' feature, and perhaps even include it in the next release of BBCSDL if it's impressive enough!

**Comment by ssb22** [comment]
Sure, we can generate such programs from any MIDI file, so take your pick ☺

For example, the music of ragtime composer Scott Joplin (1868-1917) is now out of copyright, and Benjamin Bloomfield put a Lilypond transcription of Scott Joplin's "Wall Street Rag" [into the public domain](https://github.com/MutopiaProject/MutopiaProject/blob/master/ftp/JoplinS/WallStreetRag/WallStreetRag.ly)—if we use Lilypond to convert that to a MIDI file (I had to add a bit more markup to the left-hand to make `\unfoldRepeats` work), and then use Midi Beeper to convert it to BBC BASIC, we get this:

    1REM As there are chords with three
    2REM notes per channel, you will need
    3REM BBC SDL 1.13a+ or 'real' BBCBASIC
    4REM for the ENVELOPEs to sound right.
    5REM
    6COLOUR 128:COLOUR 7:CLS
    7FOR C%=16 TO 19:SOUNDC%,0,0,0:NEXT
    8A%=-48*((INKEY(-256)AND219)=83):N%=0:DIM c%(8)
    9FOR D%=0 TO 8:c%(D%)=252:NEXT
    10REPEAT:C%=0
    11REPEAT:READ D%
    12c%(C%)=(D% AND 63)*4
    13I%=(D% DIV 64)+1:C%=C%+I%:UNTILI%=4
    14READ D%
    15REPEAT:UNTILADVAL(-6)>3
    16FOR I%=0 TO 6 STEP 3
    17S%=0:T%=0
    18IF c%(I%)=252:V%=0:ELSE IF c%(I%+1)=252:V%=1:Q%=0:R%=0:ELSE S%=1:Q%=c%(I%+1)-c%(I%):IF c%(I%+2)=252:V%=2:R%=-Q%:ELSE R%=c%(I%+2)-c%(I%+1):T%=1:V%=3
    19IF V%:V%=V%*24+55:N%=N%+1:IF N%=17:N%=1
    20IF V%:ENVELOPEN%,3,0,Q%,R%,1,S%,T%,V%,0,0,-V%,V%,V%:V%=N%
    21SOUND513+(I%DIV3),V%,c%(I%)+A%,D%
    22NEXT:UNTILD%=0:END
    23DATA141,217,15,138,214,5,131,207,10,129,205,5,131,207,5,133,209,10,134,210,20,136,212,10,133,209,10,131,207,5,133,209,5,134,210,5,138,214,10,137,213,5,136,212,20,8,136,88,224,10,63,127,63,127,255,10,1,72,141,209,5,129,143,210,5
    24DATA129,145,212,5,1,71,144,214,5,1,205,5,129,147,220,5,1,72,148,221,5,129,145,217,5,1,73,146,219,15,129,146,221,5,129,146,219,5,129,146,217,5,129,141,207,5,129,141,210,5,1,136,127,209,5,129,143,210,5,129,145,212,5,1,71,144,214,5
    25DATA1,205,5,129,147,220,5,1,72,148,221,5,129,145,217,5,1,73,146,219,10,129,146,221,5,129,146,219,5,129,146,217,5,129,146,219,5,1,72,145,221,5,129,145,212,5,0,140,127,213,5,0,127,140,209,5,9,79,145,216,5,137,17,85,221,5,5,69,21,255,5
    26DATA133,149,222,5,3,131,127,221,10,1,65,145,214,5,1,127,129,209,5,10,77,145,217,5,138,17,150,221,5,10,74,22,89,29,255,5,138,150,222,5,8,136,89,221,10,7,71,25,255,5,135,153,219,5,7,77,15,89,223,5,135,15,155,228,5,3,67,27,95,36,255,5
    27DATA131,157,229,5,7,77,15,91,31,228,5,135,15,153,226,5,8,72,24,94,34,255,5,8,127,8,127,224,5,8,76,143,222,5,136,143,219,5,0,82,148,221,5,0,127,155,255,5,8,76,143,212,5,136,143,210,5,1,72,141,209,5,129,143,210,5,129,145,212,5
    28DATA1,71,144,214,5,1,205,5,129,147,220,5,1,72,148,221,5,129,145,217,5,1,73,146,219,15,129,146,221,5,129,146,219,5,129,146,217,5,129,141,207,5,129,141,210,5,1,136,127,209,5,129,143,210,5,129,145,212,5,1,71,144,214,5,1,205,5
    29DATA129,147,220,5,1,72,148,221,5,129,145,217,5,1,73,146,219,10,129,146,217,5,129,146,219,5,129,146,217,15,129,146,219,5,1,72,145,221,5,129,145,217,5,1,139,127,212,5,129,142,214,5,10,202,5,138,22,90,29,226,5,8,72,151,29,227,5
    30DATA136,150,29,226,5,7,71,29,95,37,233,10,7,13,15,155,37,231,5,135,22,89,31,226,5,3,15,255,5,131,21,127,33,255,5,1,77,22,95,226,5,129,153,229,5,0,76,29,96,233,10,136,18,91,30,231,5,136,18,98,42,238,5,8,72,34,106,46,255,5
    31DATA136,32,105,236,5,8,76,18,93,32,233,5,136,18,91,30,231,5,1,77,25,93,37,255,10,8,89,29,255,10,193,5,1,127,148,255,5,136,140,207,5,136,140,208,5,1,72,141,209,5,129,143,210,5,129,145,212,5,1,71,144,214,5,1,205,5,129,147,220,5
    32DATA1,72,148,221,5,129,145,217,5,1,73,146,219,15,129,146,221,5,129,146,219,5,129,146,217,5,129,141,207,5,129,141,210,5,1,136,127,209,5,129,143,210,5,129,145,212,5,1,71,144,214,5,1,205,5,129,147,220,5,1,72,148,221,5,129,145,217,5
    33DATA1,73,146,219,10,129,146,221,5,129,146,219,5,129,146,217,5,129,146,219,5,1,72,145,221,5,129,145,212,5,0,140,127,213,5,0,127,140,209,5,9,79,145,216,5,137,17,85,221,5,5,69,21,255,5,133,149,222,5,3,131,127,221,10,1,65,145,214,5
    34DATA1,127,129,209,5,10,77,145,217,5,138,17,150,221,5,10,74,22,89,29,255,5,138,150,222,5,8,136,89,221,10,7,71,25,255,5,135,153,219,5,7,77,15,89,223,5,135,15,155,228,5,3,67,27,95,36,255,5,131,157,229,5,7,77,15,91,31,228,5
    35DATA135,15,153,226,5,8,72,24,94,34,255,5,8,127,8,127,224,5,8,76,143,222,5,136,143,219,5,0,82,148,221,5,0,127,155,255,5,8,76,143,212,5,136,143,210,5,1,72,141,209,5,129,143,210,5,129,145,212,5,1,71,144,214,5,1,205,5,129,147,220,5
    36DATA1,72,148,221,5,129,145,217,5,1,73,146,219,15,129,146,221,5,129,146,219,5,129,146,217,5,129,141,207,5,129,141,210,5,1,136,127,209,5,129,143,210,5,129,145,212,5,1,71,144,214,5,1,205,5,129,147,220,5,1,72,148,221,5,129,145,217,5
    37DATA1,73,146,219,10,129,146,217,5,129,146,219,5,129,146,217,15,129,146,219,5,1,72,145,221,5,129,145,217,5,1,139,127,212,5,129,142,214,5,10,202,5,138,22,90,29,226,5,8,72,151,29,227,5,136,150,29,226,5,7,71,29,95,37,233,10
    38DATA7,13,15,155,37,231,5,135,22,89,31,226,5,3,15,255,5,131,21,127,33,255,5,1,77,22,95,226,5,129,153,229,5,0,76,29,96,233,10,136,18,91,30,231,5,136,18,98,42,238,5,8,72,34,106,46,255,5,136,32,105,236,5,8,76,18,93,32,233,5
    39DATA136,18,91,30,231,5,1,77,25,93,37,255,10,8,89,29,255,10,193,15,1,151,127,227,5,6,70,22,89,30,226,10,10,13,210,10,6,6,63,25,94,34,229,10,4,132,223,10,5,133,96,37,255,10,69,8,13,17,25,32,229,10,4,4,63,25,31,63,36,255,10
    40DATA68,13,16,19,25,31,226,10,3,3,63,25,30,63,34,255,10,67,13,15,18,25,30,226,10,8,8,63,24,30,63,34,255,5,136,152,224,5,72,12,15,18,24,30,228,5,136,143,30,226,5,1,1,63,25,29,63,34,255,10,65,8,13,17,25,29,226,10,5,5,63,25,29,63,34,255,5
    41DATA133,153,224,5,1,129,93,229,5,129,151,227,5,6,70,22,89,30,226,10,10,13,210,10,6,6,63,25,94,34,229,10,4,132,223,10,5,133,96,37,255,10,69,8,13,17,25,32,229,10,4,4,63,25,31,63,36,255,10,68,13,16,19,25,31,226,10
    42DATA3,3,63,25,30,63,34,255,10,5,133,221,10,133,155,225,10,69,9,15,17,27,29,225,5,133,143,29,228,5,10,10,63,25,29,63,34,255,5,5,89,29,255,5,193,5,202,5,1,65,25,221,5,129,153,224,5,129,153,229,5,129,151,227,5,6,70,22,89,30,226,10
    43DATA10,13,210,10,6,6,63,25,94,34,229,10,4,132,223,10,5,133,96,37,255,10,69,8,13,17,25,32,229,10,4,4,63,25,31,63,36,255,10,68,13,16,19,25,31,226,10,3,3,63,25,30,63,34,255,10,67,13,15,18,25,30,226,10,8,8,63,24,30,63,34,255,5
    44DATA136,152,224,5,72,12,15,18,24,30,228,5,136,143,30,226,5,1,1,63,25,29,63,34,255,10,65,8,13,17,25,29,226,10,5,5,63,25,29,63,34,255,5,133,153,224,5,133,8,77,217,5,133,8,79,219,5,7,80,22,89,220,5,202,5,199,10,4,147,89,223,5,199,5,208,10
    45DATA19,86,25,92,226,5,208,5,205,5,202,5,208,5,205,5,202,5,199,5,136,25,221,10,8,13,17,20,89,29,224,10,8,20,63,24,191,255,5,8,146,127,219,5,8,72,18,216,5,136,146,221,5,129,17,127,217,10,17,127,157,255,5,146,222,5,147,223,5,148,224,5
    46DATA1,65,25,93,229,5,129,151,227,5,6,70,22,89,30,226,10,10,13,210,10,6,6,63,25,94,34,229,10,4,132,223,10,5,133,96,37,255,10,69,8,13,17,25,32,229,10,4,4,63,25,31,63,36,255,10,68,13,16,19,25,31,226,10,3,3,63,25,30,63,34,255,10
    47DATA67,13,15,18,25,30,226,10,8,8,63,24,30,63,34,255,5,136,152,224,5,72,12,15,18,24,30,228,5,136,143,30,226,5,1,1,63,25,29,63,34,255,10,65,8,13,17,25,29,226,10,5,5,63,25,29,63,34,255,5,133,153,224,5,1,129,93,229,5,129,151,227,5
    48DATA6,70,22,89,30,226,10,10,13,210,10,6,6,63,25,94,34,229,10,4,132,223,10,5,133,96,37,255,10,69,8,13,17,25,32,229,10,4,4,63,25,31,63,36,255,10,68,13,16,19,25,31,226,10,3,3,63,25,30,63,34,255,10,5,133,221,10,133,155,225,10
    49DATA69,9,15,17,27,29,225,5,133,143,29,228,5,10,10,63,25,29,63,34,255,5,5,89,29,255,5,193,5,202,5,1,65,25,221,5,129,153,224,5,129,153,229,5,129,151,227,5,6,70,22,89,30,226,10,10,13,210,10,6,6,63,25,94,34,229,10,4,132,223,10
    50DATA5,133,96,37,255,10,69,8,13,17,25,32,229,10,4,4,63,25,31,63,36,255,10,68,13,16,19,25,31,226,10,3,3,63,25,30,63,34,255,10,67,13,15,18,25,30,226,10,8,8,63,24,30,63,34,255,5,136,152,224,5,72,12,15,18,24,30,228,5,136,143,30,226,5
    51DATA1,1,63,25,29,63,34,255,10,65,8,13,17,25,29,226,10,5,5,63,25,29,63,34,255,5,133,153,224,5,133,8,77,217,5,133,8,79,219,5,7,80,22,89,220,5,202,5,199,10,4,147,89,223,5,199,5,208,10,19,86,25,92,226,5,208,5,205,5,202,5,208,5,205,5,202,5
    52DATA199,5,136,25,221,10,8,13,17,20,89,29,224,10,8,20,63,24,191,255,5,8,146,127,219,5,8,72,18,216,5,136,146,221,5,129,17,127,217,10,200,10,193,10,1,139,127,212,5,129,145,213,5,6,65,10,82,214,5,134,10,84,215,5,134,6,74,22,217,5
    53DATA134,134,18,214,5,1,127,18,127,22,255,5,1,205,5,1,65,6,79,18,214,10,6,127,18,127,22,255,5,6,205,5,6,65,6,78,18,214,5,134,6,207,5,1,79,18,127,22,255,5,1,208,5,1,65,6,80,18,214,5,129,6,207,5,11,79,18,127,22,255,5,11,127,143,212,5
    54DATA139,143,210,5,11,78,146,212,5,203,5,11,127,134,206,5,139,200,5,139,138,205,5,198,5,6,74,13,94,226,5,6,1,6,10,77,29,226,5,134,138,219,5,1,10,63,13,91,34,255,5,1,127,23,127,219,5,1,65,5,75,22,217,5,129,133,20,215,5,134,10,82,22,255,5
    55DATA134,10,84,215,5,134,6,74,22,217,5,134,134,18,214,5,1,127,18,127,22,255,5,1,205,5,1,65,6,79,18,214,10,6,127,18,127,22,255,5,6,205,5,6,70,14,210,5,134,207,5,7,79,18,255,5,7,77,208,5,7,71,13,208,5,135,13,209,5,8,77,17,255,5
    56DATA136,145,212,5,8,72,13,81,211,5,136,141,212,5,8,82,20,127,216,5,8,84,152,221,5,8,72,20,216,5,136,146,219,5,1,81,23,255,10,129,151,217,10,1,65,11,81,212,10,129,139,213,10,134,10,82,214,5,134,10,84,215,5,134,6,74,22,217,5
    57DATA134,134,18,214,5,1,127,18,127,22,255,5,1,205,5,1,65,6,79,18,214,10,6,127,18,127,22,255,5,6,205,5,6,65,6,78,18,214,5,134,6,207,5,1,79,18,127,22,255,5,1,208,5,1,70,10,80,18,214,5,129,10,207,5,11,79,18,127,22,255,5,11,127,143,212,5
    58DATA131,143,210,5,3,79,146,212,5,11,75,15,210,10,139,15,81,213,10,10,74,142,214,5,138,142,22,218,5,10,5,138,22,26,221,5,138,142,26,226,5,8,8,14,17,22,255,5,72,63,14,127,17,255,5,8,69,8,74,14,214,10,7,71,15,127,22,255,10
    59DATA131,13,83,25,219,5,131,141,25,220,5,3,67,19,89,28,255,5,3,127,3,127,219,5,7,77,15,91,31,227,5,135,15,153,226,5,8,72,24,94,34,255,5,136,24,127,219,5,8,76,15,88,222,5,136,143,30,224,5,3,67,24,94,32,255,5,131,24,127,226,5
    60DATA4,132,94,224,10,5,69,25,93,226,5,133,153,224,5,11,77,17,89,221,5,139,145,29,229,5,1,65,25,93,37,255,5,129,153,227,5,11,77,17,87,219,5,139,145,221,5,6,70,22,89,222,10,5,197,5,3,195,5,1,193,5,129,10,127,210,5,129,11,81,212,5
    61DATA129,139,213,5,134,10,82,214,5,134,10,84,215,5,134,6,74,22,217,5,134,134,18,214,5,1,127,18,127,22,255,5,1,205,5,1,65,6,79,18,214,10,6,127,18,127,22,255,5,6,205,5,6,65,6,78,18,214,5,134,6,207,5,1,79,18,127,22,255,5,1,208,5
    62DATA1,65,6,80,18,214,5,129,6,207,5,11,79,18,127,22,255,5,11,127,143,212,5,139,143,210,5,11,78,146,212,5,203,5,11,127,134,206,5,139,200,5,139,138,205,5,198,5,6,74,13,94,226,5,6,1,6,10,77,29,226,5,134,138,219,5,1,10,63,13,91,34,255,5
    63DATA1,127,23,127,219,5,1,65,5,75,22,217,5,129,133,20,215,5,134,10,82,22,255,5,134,10,84,215,5,134,6,74,22,217,5,134,134,18,214,5,1,127,18,127,22,255,5,1,205,5,1,65,6,79,18,214,10,6,127,18,127,22,255,5,6,205,5,6,70,14,210,5,134,207,5
    64DATA7,79,18,255,5,7,77,208,5,7,71,13,208,5,135,13,209,5,8,77,17,255,5,136,145,212,5,8,72,13,81,211,5,136,141,212,5,8,82,20,127,216,5,8,84,152,221,5,8,72,20,216,5,136,146,219,5,1,81,23,255,10,129,151,217,10,1,65,11,81,212,10
    65DATA129,139,213,10,134,10,82,214,5,134,10,84,215,5,134,6,74,22,217,5,134,134,18,214,5,1,127,18,127,22,255,5,1,205,5,1,65,6,79,18,214,10,6,127,18,127,22,255,5,6,205,5,6,65,6,78,18,214,5,134,6,207,5,1,79,18,127,22,255,5,1,208,5
    66DATA1,70,10,80,18,214,5,129,10,207,5,11,79,18,127,22,255,5,11,127,143,212,5,131,143,210,5,3,79,146,212,5,11,75,15,210,10,139,15,81,213,10,10,74,142,214,5,138,142,22,218,5,10,5,138,22,26,221,5,138,142,26,226,5,8,8,14,17,22,255,5
    67DATA72,63,14,127,17,255,5,8,69,8,74,14,214,10,7,71,15,127,22,255,10,131,13,83,25,219,5,131,141,25,220,5,3,67,19,89,28,255,5,3,127,3,127,219,5,7,77,15,91,31,227,5,135,15,153,226,5,8,72,24,94,34,255,5,136,24,127,219,5,8,76,15,88,222,5
    68DATA136,143,30,224,5,3,67,24,94,32,255,5,131,24,127,226,5,4,132,94,224,10,5,69,25,93,226,5,133,153,224,5,11,77,17,89,221,5,139,145,29,229,5,1,65,25,93,37,255,5,129,153,227,5,11,77,17,87,219,5,139,145,221,5,6,70,22,89,222,10
    69DATA10,86,25,255,5,195,5,6,70,22,217,10,7,127,7,127,219,5,135,135,220,5,136,136,221,5,8,72,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5,1,127,129,221,5,1,65,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5,8,127,136,221,5
    70DATA8,72,32,99,37,231,5,11,13,209,5,75,63,17,98,35,229,5,129,34,99,37,255,5,1,127,13,127,224,5,139,139,219,5,139,139,221,5,138,138,222,5,10,74,34,101,231,5,10,77,18,127,219,5,138,146,221,5,1,127,129,222,5,1,65,34,101,231,5
    71DATA10,77,18,127,219,5,138,146,221,5,6,127,134,222,5,6,70,32,98,229,5,10,77,18,96,34,229,10,129,32,98,37,255,5,1,127,13,127,222,5,10,77,146,221,5,138,146,222,5,10,127,138,223,5,10,74,34,101,232,5,7,77,15,127,221,5,135,143,222,5
    72DATA3,191,127,223,5,3,79,34,101,232,5,1,127,13,127,221,5,1,77,31,98,231,5,11,75,32,227,5,139,226,5,136,15,98,35,231,10,8,72,34,99,39,255,5,8,127,8,127,224,5,8,75,143,226,5,136,143,227,5,9,127,137,228,5,9,73,167,233,5,12,79,145,225,5
    73DATA140,145,226,5,5,127,133,228,5,5,69,167,233,5,9,79,145,225,5,137,17,100,39,233,5,10,74,34,101,41,255,10,10,77,17,98,37,233,10,10,74,25,92,31,229,10,7,127,7,127,27,255,5,135,135,220,5,136,136,221,5,8,72,32,99,37,231,5
    74DATA11,77,17,127,27,255,5,139,145,220,5,1,127,129,221,5,1,65,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5,8,127,136,221,5,8,72,32,99,37,231,5,11,13,209,5,75,63,17,98,35,229,5,129,34,99,37,255,5,1,127,13,127,224,5,139,139,219,5
    75DATA139,139,221,5,138,138,222,5,10,74,34,101,231,5,10,77,18,127,219,5,138,146,221,5,1,127,129,222,5,1,65,34,101,231,5,10,77,18,127,219,5,138,146,221,5,6,127,134,222,5,6,70,32,98,229,5,10,77,18,96,34,229,10,129,32,98,37,255,5
    76DATA1,127,13,127,222,5,10,77,146,221,5,138,146,222,5,10,127,138,223,5,10,74,34,101,232,5,7,77,15,127,221,5,135,143,222,5,3,191,127,223,5,3,79,34,101,232,5,1,127,13,127,221,5,1,77,31,98,231,5,11,75,32,227,5,139,226,5,136,15,98,35,231,10
    77DATA3,79,34,99,39,255,5,131,224,5,2,78,33,100,234,10,1,77,34,229,5,129,34,127,231,5,138,18,98,229,5,138,18,127,226,5,1,65,25,221,5,129,151,224,5,11,77,17,87,29,224,5,139,145,29,233,5,6,70,22,89,30,255,10,10,86,25,255,5,193,5
    78DATA6,70,22,217,10,7,127,7,127,219,5,135,135,220,5,136,136,221,5,8,72,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5,1,127,129,221,5,1,65,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5,8,127,136,221,5,8,72,32,99,37,231,5
    79DATA11,13,209,5,75,63,17,98,35,229,5,129,34,99,37,255,5,1,127,13,127,224,5,139,139,219,5,139,139,221,5,138,138,222,5,10,74,34,101,231,5,10,77,18,127,219,5,138,146,221,5,1,127,129,222,5,1,65,34,101,231,5,10,77,18,127,219,5,138,146,221,5
    80DATA6,127,134,222,5,6,70,32,98,229,5,10,77,18,96,34,229,10,129,32,98,37,255,5,1,127,13,127,222,5,10,77,146,221,5,138,146,222,5,10,127,138,223,5,10,74,34,101,232,5,7,77,15,127,221,5,135,143,222,5,3,191,127,223,5,3,79,34,101,232,5
    81DATA1,127,13,127,221,5,1,77,31,98,231,5,11,75,32,227,5,139,226,5,136,15,98,35,231,10,8,72,34,99,39,255,5,8,127,8,127,224,5,8,75,143,226,5,136,143,227,5,9,127,137,228,5,9,73,167,233,5,12,79,145,225,5,140,145,226,5,5,127,133,228,5
    82DATA5,69,167,233,5,9,79,145,225,5,137,17,100,39,233,5,10,74,34,101,41,255,10,10,77,17,98,37,233,10,10,74,25,92,31,229,10,7,127,7,127,27,255,5,135,135,220,5,136,136,221,5,8,72,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5
    83DATA1,127,129,221,5,1,65,32,99,37,231,5,11,77,17,127,27,255,5,139,145,220,5,8,127,136,221,5,8,72,32,99,37,231,5,11,13,209,5,75,63,17,98,35,229,5,129,34,99,37,255,5,1,127,13,127,224,5,139,139,219,5,139,139,221,5,138,138,222,5
    84DATA10,74,34,101,231,5,10,77,18,127,219,5,138,146,221,5,1,127,129,222,5,1,65,34,101,231,5,10,77,18,127,219,5,138,146,221,5,6,127,134,222,5,6,70,32,98,229,5,10,77,18,96,34,229,10,129,32,98,37,255,5,1,127,13,127,222,5,10,77,146,221,5
    85DATA138,146,222,5,10,127,138,223,5,10,74,34,101,232,5,7,77,15,127,221,5,135,143,222,5,3,191,127,223,5,3,79,34,101,232,5,1,127,13,127,221,5,1,77,31,98,231,5,11,75,32,227,5,139,226,5,136,15,98,35,231,10,3,79,34,99,39,255,5,131,224,5
    86DATA2,78,33,100,234,10,1,77,34,229,5,129,34,127,231,5,138,18,98,229,5,138,18,127,226,5,1,65,25,221,5,129,151,224,5,11,77,17,87,29,224,5,139,145,29,233,5,6,70,22,89,30,255,10,1,86,25,255,10,6,94,34,101,234,10,255,0

**Comment by rtrussell** [comment]
I'll try it.  As I'm sure you know, 'The Entertainer' and 'Fig Leaf Rag' are supplied as example programs with _BBC BASIC for SDL 2.0_, but they were transcribed for four voices back in the early 1980s so don't need any tricks other than the option of converting channel 0 to be a fourth tone channel.
