### ISSUE TITLE
How to use SYS with shared object file?

### ISSUE THREAD

**Issue by rchee2018** [rtrussell/BBCSDL#41]
Hi, I am just a amatuer learning BCCSDL on my macos.

I have the following code, but the final line throws an "address out of range" error:

```
sys "SDL_LoadObject", "libmylib.so" to mylib
sys "SDL_LoadFunction", "mylib", "mymod" to `mymod`
sys `mymod`, 42 to index
```

I do not understand how the error happens and how to debug this.

The file "libmylib.so" came from a simple code, as below (mymod.c):
```
#include <stdio.h>
void mymod( int x)
{
    printf( "mymod: %d\n", x );
}
```

I did the following to turn it into libmylib.so:
```
gcc -o mymod.o -c mymod.c
```
then 
```
gcc -shared -o libmylib.so mymod.o -lm
```

I tested libmylib.so using this code (callmymod.c):
```
extern void mymod( int x);
int main (int argc, char** argv)
{
    mymod (42);
}
```

And the code to link the two:
```
gcc callmymod.c -lmylib -L.
```

When I ran the final executable, I got `mymod: 42`.

However, I cannot reproduce this on BBCSDL with the code I showed at the top.
Where did I go wrong? It must be something simple but not obvious for someone untrained in computer science.
I would really appreciate some pointers from the developers of BBCSDL!

**Comment by rtrussell** [comment]
> I have the following code, but the final line throws an "address out of range" error:
> 
> ```
> sys "SDL_LoadObject", "libmylib.so" to mylib
> sys "SDL_LoadFunction", "mylib", "mymod" to `mymod`
> sys `mymod`, 42 to index
> ```

The second line should be:

`SYS "SDL_LoadFunction", mylib, "mymod" TO mymod`

i.e. `mylib` (numeric) not `"mylib"` (string).

I would recommend checking the returned value for being zero (NULL) to give you early warning that something has gone wrong:

```
SYS "SDL_LoadFunction", mylib, "mymod" TO mymod
IF mymod = 0 PRINT "Oops" : STOP
```

**Comment by rchee2018** [comment]
Thank you for your suggestion, Mr Russell.
I see the idea behind the returned value now.

The code (as follows) triggers the "Oops", unfortunately.

```
sys "SDL_LoadObject", "libmylib.so" to mylib
sys "SDL_LoadFunction", mylib, "mymod" to mymod
if mymod = 0 print "Oops" : stop
sys mymod, 42 to index
```

**Comment by rtrussell** [comment]
> The code (as follows) triggers the "Oops", unfortunately.

There's nothing wrong with that code, that I can see.  Either it is failing to load the shared object (check whether `mylib` is zero) or the function `"mymod"` is not being exported.  I assume the .so is being built in plain C and not C++, if it's C++ the 'name mangling' will mean the exported name is not the same as the function name.

**Comment by rchee2018** [comment]
> (check whether mylib is zero) 

No, it is not zero. I put another check there and it did not alert.

> or the function "mymod" is not being exported.

This might be it. I will try with a different shared object library. Another comment to come.

> I assume the .so is being built in plain C and not C++

Well, I used `gcc` (not `g++`) to compile. I think my code looks like C, rather than C++.

The other thing I wondered is whether the `printf` in the C code caused a confounding problem.

**Comment by rchee2018** [comment]
This time I decided to make a new shared object library, and compile using `clang`.

myval.c
``` 
int myval ( int x )
{
    return x * 10;
}
```

And compiled it with the code:
```
clang myval.c -o libmyval.so -fPIC -shared 
```

And I tested it with getmyval.c (code below). It printed the expected `Value: 80`.

getmyval.c
```
#include <studio.h>
extern int myval(int x);

int main ()
{
    printf( "Value: %d\n", myval(8) );
    return 0;
}
```

However, when tested on BBCSDL with the following, it stopped at "Oops".

```
      sys "SDL_LoadObject", "libmyval.so" to myobj
      if myobj = 0 print "Ahhh" : stop
      sys "SDL_LoadFunction", myobj, "myval" to myval
      if myval = 0 print "Oops" : stop
      print myval,5
```

Since getmyval works, I doubt it is the library failing to be exported.

Either way, this is probably the end of the trail for now...
 
I thank you for the help that you have provided.
Maybe the solution will present itself one day.

**Comment by rtrussell** [comment]
> Since getmyval works, I doubt it is the library failing to be exported.

Please use the tool described [here](https://stackoverflow.com/questions/34732/how-do-i-list-the-symbols-in-a-so-file) to list the symbols being exported by your .so.

> Either way, this is probably the end of the trail for now...

What you are attempting is standard functionality, and is used by the supplied **box2dlib.bbc** library.  If the Box2D examples in `examples/physics/` are working, it proves that there's nothing wrong with importing a function from a .so.

I still strongly suspect you are not exporting the function.   Shouldn't your code have a `__attribute__((visibility("default")))` to achieve that?  Functions are not exported by default; it's common practice to use code like this to define the symbol EXPORT for multiple platforms:

```
#if defined(_MSC_VER)
    //  Microsoft 
    #define EXPORT __declspec(dllexport)
#else
    //  GCC
    #define EXPORT __attribute__((visibility("default")))
#endif
```

**Comment by rchee2018** [comment]
> Please use the tool described [here](https://stackoverflow.com/questions/34732/how-do-i-list-the-symbols-in-a-so-file) to list the symbols being exported by your .so.

Thanks. Using the `nm` tool, I get the following:

`nm libmylib.so`

```
0000000000008008 d __dyld_private
0000000000003f60 T _mymod
                 U _printf
                 U dyld_stub_binder
```
`nm libmyval.so`

```
0000000000003fa0 T _myval
                 U dyld_stub_binder
```

**Comment by rtrussell** [comment]
> Thanks. Using the `nm` tool, I get the following:
> 0000000000003fa0 T _myval

That means you're exporting the function as "_myval", not "myval", doesn't it?

**Comment by rchee2018** [comment]
No, the "_myval" is the name of the symbol representing the function "myval". Documented [here](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/executing_files.html).

For what it is worth, I tried the symbol name, and made not difference to the outcome.

Sorry. 

I will try the Box2D examples when I can. It is 6 past midnight here.

**Comment by rchee2018** [comment]
Maybe we've both been going down the wrong path.

I checked the `box2dlib.bbc` code just now.
On my macos, `print (@platform% and &F)` gives me 2.
Which is

> when 2: sys "SDL_LoadObject", @lib$ + "../../Frameworks/Box2D231.dylib" to Box2D@%%   

That means, I should be making a `.dylib` instead of `.so`.

I will do more testing by attempting to create a `.dylib` and see how far that gets us.

I hear there's a nice Aurora happening in the northern hemisphere. Hope you get a view!

**Comment by rchee2018** [comment]
Good news!

```
      sys "SDL_LoadObject", "libmyval.so" to myobj@%%
      if myobj@%% = 0 print "Ahhh" : stop
      sys "SDL_LoadFunction", myobj@%%, "myval" to myval%%
      if myval%% = 0 print "Oops" : stop
      sys myval%%,7 to message
      print str$(message)
```

Works! (prints `70` as expected).
The suffixes did the trick (copied the suffixes from `box2dlib.bbc`).

So, I am wrong again. Although `box2dlib.bbc` would be coded to use `dylib`, the code above works with `so`.

I am still awake, so I will do more testing and learning.

**Comment by rchee2018** [comment]
The first code I posted (the one using `libmylib.so`), was a challenge to verify.
The shared object has incorporated the `printf` function.
It would print to stdout.
When called in BBCSDL, there was no error messages.
Since the expected output destination is stdout, it cannot be checked by watching the immediate-mode window.

However, the code below works!

test5.bbc
```
      sys "SDL_LoadObject", "libmylib.so" to mylib@%%
      if mylib@%% = 0 print "Ahhh" : stop
      sys "SDL_LoadFunction", mylib@%%, "mymod" to mymod%%
      if mymod%% = 0 print "Oops" : stop
      sys mymod%%, 42
```

It can be verified on the macos *Terminal* by running
```
/Applications/BBCBasic.app/Contents/MacOS/BBCBasic test5.bbc 
```
This resulted in opening of the immediate-mode window, and in printing of `mymod: 42` on the *Terminal*.

**Comment by rchee2018** [comment]
Further testing by creating a `dylib` file has also worked (verified by the same *Terminal* method above)!

So, I am happy that I can use BBCSDL to access `so` and `dylib` dynamically.

What I have learned:
1. Check whether returned value is zero (NULL).
2. Apply the variable type suffix (@%% and %%).
3. Use `nm` tool to check symbols.
4. Example codes are educational.
5. BBCSDL deals well with `so` file and `dylib` alike.

I almost gave up, but thanks to Mr Russell for egging me on.

This problem is solved.

**Comment by rtrussell** [comment]
> This problem is solved.

Glad you got there in the end!
