### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Rob-McKay** [rtrussell/BBCSDL#6]
Hi Richard,

I believe that you have some tests to ensure that BBCSDL is working correctly but I cannot seem to be able to find them in this repo.

Would it be possible for you to include them?

Many thanks,

Rob

**Comment by rtrussell** [comment]
> I believe that you have some tests to ensure that BBCSDL is working correctly

I'm afraid I don't, nothing that amounts to a comprehensive test suite (or anything close) anyway.  I have dozens of individual programs that were written to test specific features when they were first implemented, but that's all; many of those don't report a pass/fail.  An automated test suite would be a great way to protect against regressions, but writing one would be a massive exercise.  I'm not even aware that Sophie Wilson had such a thing for her BASICs, but I don't know for sure.  Sorry.

**Comment by rtrussell** [comment]
Just to add that only recently a serious bug was discovered, causing FOR...NEXT loops with a negative non-integer STEP to fail completely on ARM platforms.  It's fixed now, but a test suite would have found that for sure!

**Comment by rtrussell** [comment]
What I will do is create a 'tests' directory in the repository into which I will copy any existing non-trivial test programs which seem valuable.  Over time perhaps this will build into a useful suite.  Thanks for the suggestion.
